
export const UPDATE_ADDRESS = 'UPDATE_ADDRESS'

export const REFRESH_BALANCE = 'REFRESH_BALANCE'

export const BALANCE_REFRESHED = 'BALANCE_REFRESHED'

export const WALLET_CREATED = 'WALLET_CREATED'
